export const GET_GROCERY_DATA_REQUEST = "GET_GROCERY_DATA_REQUEST"
export const GET_GROCERY_DATA_SUCCESS = "GET_GROCERY_DATA_SUCCESS"
export const GET_GROCERY_DATA_FAILED = "GET_GROCERY_DATA_FAILED"

export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";