export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const GET_MEETUPS_DATA_REQUEST = "GET_MEETUPS_DATA_REQUEST";
export const GET_MEETUPS_DATA_SUCCESS = "GET_MEETUPS_DATA_SUCCESS";
export const GET_MEETUPS_DATA_FAILURE = "GET_MEETUPS_DATA_FAILURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const SUBSCRIBE_EVENT_REQUEST = "SUBSCRIBE_EVENT_REQUEST";
export const SUBSCRIBE_EVENT_SUCCESS = "SUBSCRIBE_EVENT_SUCCESS";
export const SUBSCRIBE_EVENT_FAILURE = "SUBSCRIBE_EVENT_FAILURE";